name: Upload Package to PyPI

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    if: github.repository == 'DennisGross/gimitest'
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      - name: Build a binary wheel and a source tarball
        run: python -m build --outdir dist/ .

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: releases
          path: dist/

  upload-to-pypi:
    if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
    needs: build-artifacts
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/gimitest

    permissions:
      id-token: write

    steps:
      - name: Download the artifacts
        uses: actions/download-artifact@v4
        with:
          name: releases
          path: dist/

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true